### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by beckettsean** [ajgb/anyevent-influxdb#4]
I'm cleaning up the https://docs.influxdata.com/influxdb/v1.0/tools/api_client_libraries/ page and removing those libraries that aren't compatible with InfluxDB 1.0. 

I'll remove this project from that page on October 15th unless you have plans to update for 1.0 compatibility. Thanks!

**Comment by ajgb** [comment]
Yep, still active - I've got 1.0 branch already released.

Just waiting for 1.1 to be released - any time soon? Any breaking changes in pipeline?

But if you are in hurry I can push 1.0 in next couple of days.

**Comment by beckettsean** [comment]
Great news, @ajgb! 1.1 will be a November release, and there will be no breaking changes for the duration of the 1.x version line. Only additive changes are permitted. We may add new keywords, but as long as you are double-quoting identifiers when passing them that won't be a breaking change.

No real rush from our end, but if 1.0 is ready to go no reason to hold it back. It will work with 1.1, it just may not support the new features: https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#features

**Comment by ajgb** [comment]
As you probably have seen I try to provide wrappers for every query available, so I need to make sure that I update the SQL syntax generators up to date - and that's what takes most of time (and testing of course!).

I'll then wrap it all up and release it in next few days.

Thanks @beckettsean!

BTW I'm tracking InfluxDB since v0.8 and was very happy when you got finally stable enough to promote you within my organisation - https://github.com/ajgb/go-opsview

**Comment by beckettsean** [comment]
I've been supporting InfluxDB since v0.8 and I'm really happy that 1.0 is stable enough, too!

Thanks for your contributions and your support! Can we send you a t-shirt or some stickers? Drop a note to contact@influxdb.com and tell them I sent you ;)

**Comment by ajgb** [comment]
I surely will! Thanks @beckettsean, that's very nice of you.
